// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pg

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CheckState string

const (
	CheckStatePending CheckState = "pending"
	CheckStateSuccess CheckState = "success"
	CheckStateFailure CheckState = "failure"
	CheckStateError   CheckState = "error"
)

func (e *CheckState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CheckState(s)
	case string:
		*e = CheckState(s)
	default:
		return fmt.Errorf("unsupported scan type for CheckState: %T", src)
	}
	return nil
}

type NullCheckState struct {
	CheckState CheckState `json:"check_state"`
	Valid      bool       `json:"valid"` // Valid is true if CheckState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCheckState) Scan(value interface{}) error {
	if value == nil {
		ns.CheckState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CheckState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCheckState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CheckState), nil
}

type EntryState string

const (
	EntryStateQueued    EntryState = "queued"
	EntryStateTesting   EntryState = "testing"
	EntryStateSuccess   EntryState = "success"
	EntryStateFailed    EntryState = "failed"
	EntryStateCancelled EntryState = "cancelled"
)

func (e *EntryState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EntryState(s)
	case string:
		*e = EntryState(s)
	default:
		return fmt.Errorf("unsupported scan type for EntryState: %T", src)
	}
	return nil
}

type NullEntryState struct {
	EntryState EntryState `json:"entry_state"`
	Valid      bool       `json:"valid"` // Valid is true if EntryState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEntryState) Scan(value interface{}) error {
	if value == nil {
		ns.EntryState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EntryState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEntryState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EntryState), nil
}

type CheckStatus struct {
	ID           int64              `json:"id"`
	QueueEntryID int64              `json:"queue_entry_id"`
	Context      string             `json:"context"`
	State        CheckState         `json:"state"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	TargetUrl    string             `json:"target_url"`
}

type QueueEntry struct {
	ID               int64              `json:"id"`
	RepoID           int64              `json:"repo_id"`
	PrNumber         int64              `json:"pr_number"`
	PrHeadSha        string             `json:"pr_head_sha"`
	TargetBranch     string             `json:"target_branch"`
	State            EntryState         `json:"state"`
	EnqueuedAt       pgtype.Timestamptz `json:"enqueued_at"`
	TestingStartedAt pgtype.Timestamptz `json:"testing_started_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	MergeBranchName  pgtype.Text        `json:"merge_branch_name"`
	MergeBranchSha   pgtype.Text        `json:"merge_branch_sha"`
	ErrorMessage     pgtype.Text        `json:"error_message"`
}

type Repo struct {
	ID        int64              `json:"id"`
	Owner     string             `json:"owner"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
